#! /bin/sh

pkill sxhkd
sxhkd -c ~/.config/sxhkd/bspwm -m -1 &

pkill xsettingsd
xsettingsd &

picom -b --no-fading-openclose

pkill dunst
dunst &

pkill xss-lock
xss-lock ~/.lock.sh &
xset s 300

$HOME/.config/polybar/launch.sh

hsetroot -solid "#383c4a"

pkill unclutter
unclutter --timeout 4 --ignore-scrolling -b

pkill pia-client
/opt/piavpn/bin/pia-client --quiet &

pkill blueman-applet
blueman-applet &

pkill nm-applet
nm-applet &

pkill blueman-applet
blueman-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1

bspc config window_gap 5
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a 'firefox:*:Picture-in-Picture' state=floating
