#! /bin/sh

pkill sxhkd
sxhkd -c ~/.config/sxhkd/bspwm -m -1 &

pkill xsettingsd
xsettingsd &

picom -b --no-fading-openclose

pkill dunst
dunst &

pkill xss-lock
xss-lock ~/.lock.sh &
xset s 300

$HOME/.config/polybar/launch.sh

hsetroot -cover ~/.bg.jpg

pkill unclutter
unclutter --timeout 4 --ignore-scrolling -b

pkill blueman-applet
blueman-applet &

pkill nm-applet
nm-applet &

pkill blueman-applet
blueman-applet &

polkit-dumb-agent &

bspc monitor -d I II III IV

bspc config border_width 1

bspc config window_gap 5
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a 'firefox:*:Picture-in-Picture' state=floating

# fancy colors!

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"
